name: cupertino_date_picker
description: Customizable cupertino date picker.
version: 1.0.0
homepage: 'https://github.com/Dihardja-Software/date-picker-component'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
